package com.example.tarotapp.db.cards.files

class WeeklyReading {
    companion object {
        public var weeklyReading = "0,1,'This week is a good time to take initiative and approach situations with a beginner`s mind.  The Fool encourages you to experiment and explore new ways of using your skills, while the Magician suggests you can be resourceful and learn quickly.'\n" +
                "0,2,'Trust your intuition and inner wisdom this week. The Fool encourages you to embrace new experiences with an open mind, while the High Priestess suggests your gut feeling will guide you well.'\n" +
                "0,3,'A time for creativity, nurturing new projects, and fostering positive relationships. The Fool encourages you to approach these endeavors with a childlike sense of wonder, and the Empress highlights the importance of care and compassion.'\n" +
                "0,4,'This week may involve taking on a leadership role or starting a new venture. The Fool encourages you to be bold and innovative in your approach, while the Emperor suggests the importance of structure and planning.'\n" +
                "0,5,'Be open to learning from new teachers or mentors this week. The Fool encourages you to embrace new ideas and perspectives, and the Hierophant signifies the opportunity to gain valuable knowledge.'\n" +
                "0,6,'New love connections or a fresh start in an existing relationship are possible this week. The Fool encourages you to approach love with openness and enthusiasm, and the Lovers highlight the importance of connection and commitment.'\n" +
                "0,7,'This week is about setting new goals and taking action to achieve them. The Fool encourages you to pursue your aspirations with enthusiasm, and the Chariot signifies determination and focus.'\n" +
                "0,8,'You may need to overcome challenges or face your fears this week. The Fool encourages you to approach these situations with courage and optimism, and Strength highlights your inner resources that will help you persevere.'\n" +
                "0,9,'Taking time for introspection and solitude can be beneficial this week. The Fool encourages you to disconnect from distractions and reconnect with yourself, and the Hermit signifies the value of self-reflection.'\n" +
                "0,10,'Expect unexpected opportunities and changes in direction this week. The Fool encourages you to embrace these shifts with a sense of adventure, and the Wheel of Fortune signifies the ever-turning nature of life.'\n" +
                "0,11,'A situation requiring fairness or honesty may arise this week. The Fool encourages you to approach it with an open mind and a willingness to see all sides, and Justice signifies the importance of acting with integrity.'\n" +
                "0,12,'Consider alternative perspectives and be open to new ways of thinking this week. The Fool encourages you to challenge your assumptions, and the Hanged Man signifies the value of looking at things from a different angle.'\n" +
                "0,13,'This week may involve endings or transformations that pave the way for new beginnings. The Fool encourages you to embrace change with a positive outlook, and Death signifies letting go of the past to make room for the future.'\n" +
                "0,14,'The Fool represents new beginnings, leaps of faith, and taking chances. Temperance signifies balance, moderation, and finding the middle way. This combination suggests that before embarking on a new venture this week, it`s important to find balance in various aspects of your life.'\n" +
                "0,15,'Beware of impulsive decisions or getting caught up in limitations this week. The Fool encourages you to be cautious and avoid being tempted by shortcuts, and the Devil highlights the importance of staying true to your values.'\n" +
                "0,16,'Sudden disruptions or unexpected changes may occur this week. The Fool encourages you to see these events as opportunities for growth, and the Tower signifies the need to adapt and rebuild.'\n" +
                "0,17,'Maintain hope and faith in your dreams this week, even if the path seems unclear. The Fool encourages you to believe in the possibilities, and the Star signifies the potential for achieving your goals.'\n" +
                "0,18,'This pairing can represent a time of uncertainty, illusion, and a lack of clear direction, influenced by the Moon`s themes. The Fool signifies new beginnings and taking a leap of faith, but the Moon`s influence can cause hesitation or doubt.'\n" +
                "0,19,'Embrace new beginnings with enthusiasm and optimism. Follow your inner compass, radiate joy, and share your happiness with others. This is a time to tap into your inner child`s wonder and create a week filled with laughter, success, and positive experiences.'\n" +
                "0,20,'It`s crucial to take time for reflection and self-evaluation before taking the leap. Ensure you`re letting go of the past, making well-informed choices, and facing any fears that might be holding you back. By approaching new beginnings with wisdom and a sense of discernment, you can set yourself up for a successful and fulfilling journey.'\n" +
                "0,21,'This week may culminate in a sense of accomplishment or completion of a significant cycle. The Fool encourages you to celebrate your achievements and embrace new beginnings, and the World signifies a feeling of wholeness and fulfillment.'\n" +
                "1,2,'A time to combine intuition with action.  The Magician encourages you to take initiative based on your gut feelings, using your skills to manifest your inner wisdom.'\n" +
                "1,3,'Express your creativity and nurture new projects with resourcefulness. The Magician highlights using your skills for creative endeavors, while the Empress signifies nurturing these projects with care and compassion.'\n" +
                "1,4,'This week is about taking a leadership role and implementing your ideas with structure. The Magician encourages you to use your skills effectively, and the Emperor emphasizes the importance of organization and planning.'\n" +
                "1,5,'A chance to learn new skills or share your knowledge with others. The Magician signifies acquiring or using knowledge, and the Hierophant highlights learning from teachers or becoming a teacher yourself.'\n" +
                "1,6,'This week may involve using your skills to improve communication or resolve relationship issues. The Magician emphasizes communication and resourcefulness, while the Lovers highlight the importance of connection and understanding.'\n" +
                "1,7,'A powerful combination for achieving your goals through focused action and resourcefulness. The Magician highlights using your skills effectively, and the Chariot emphasizes determination and focus.'\n" +
                "1,8,' This week may require using your skills and inner strength to overcome challenges. The Magician emphasizes resourcefulness and willpower, while Strength highlights your inner resources that will help you persevere.'\n" +
                "1,9,'A time for focused work and honing your skills in solitude. The Magician encourages you to dedicate time to refining your abilities, and the Hermit signifies the value of concentrated effort.'\n" +
                "1,10,'Adapting your skills and approach to navigate unexpected opportunities this week. The Magician encourages resourcefulness, and the Wheel of Fortune signifies the need to be flexible as circumstances change.'\n" +
                "1,11,'A situation requiring fairness and balanced use of your skills may arise. The Magician encourages ethical use of your abilities, and Justice highlights acting with integrity.'\n" +
                "1,12,'Consider alternative approaches and use your skills to find creative solutions this week. The Magician encourages innovative thinking, and the Hanged Man signifies the value of looking at things from a different angle.'\n" +
                "1,13,'Letting go of outdated skills or approaches and embracing new ways of doing things. The Magician signifies transformation of your skillset, and Death highlights the need to release the old to make way for the new.'\n" +
                "1,14,'Using your skills and resources with balance and moderation. Don`t exhaust yourself by trying to do too much. Find an efficient and sustainable approach.'\n" +
                "1,15,'Beware of manipulating others or using your skills for personal gain. The Magician encourages ethical use of your abilities, and the Devil highlights the importance of avoiding temptation and staying true to your values.'\n" +
                "1,16,'Sudden disruptions may require you to adapt your skills and approach to a situation. The Magician encourages resourcefulness in the face of change, and the Tower signifies the need to rebuild.'\n" +
                "1,17,'This week is about using your skills and talents to bring your dreams to life. The Magician highlights manifesting your desires through action, and the Star signifies the potential for achieving your goals.'\n" +
                "1,18,'Deception or illusion surrounding your skills or resources. The Magician signifies skill and resourcefulness, and the Moon highlights illusion. This week, be cautious of misinformation or misrepresenting your skills.'\n" +
                "1,19,'This combination suggests that the querent has the ability to manifest their desires and achieve success in their endeavors. The Magician`s manifestation power pairs well with The Sun`s success and vitality, creating a potent combination of action and achievement.'\n" +
                "1,20,'Trust your abilities, approach challenges with discernment, and be willing to adapt your approach if needed. By making wise choices and letting go of limitations, you can manifest positive outcomes and achieve your goals.'\n" +
                "1,21,'A sense of accomplishment and fulfillment through using your skills to achieve your goals. The Magician signifies mastery and achievement, and the World signifies a feeling of wholeness and living your purpose.'\n" +
                "2,3,'Nurturing your intuition and creativity.  The High Priestess encourages you to connect with your inner wisdom, and the Empress signifies using that intuition to nurture creative projects or relationships.'\n" +
                "2,4,'Following your intuition when making decisions or leading others. The High Priestess encourages you to trust your gut feelings, and the Emperor highlights the importance of using your intuition to guide your leadership.'\n" +
                "2,5,'Seeking guidance from a wise teacher or mentor who resonates with your intuition. The High Priestess highlights the importance of finding a teacher who aligns with your inner wisdom, and the Hierophant signifies the act of learning from such a figure.'\n" +
                "2,6,'Following your heart and intuition in your relationships. The High Priestess encourages you to trust your gut feelings about love connections, and the Lovers highlight the importance of genuine connection.'\n" +
                "2,7,'Following your intuition when setting goals and taking action. The High Priestess encourages you to trust your inner wisdom when pursuing your aspirations, and the Chariot signifies determination and focus aligned with your intuition.'\n" +
                "2,8,'Finding inner strength and trusting your intuition to navigate challenges. The High Priestess encourages you to connect with your inner wisdom, and Strength highlights the inner resources that will help you persevere based on that guidance.'\n" +
                "2,9,'A time for introspection and solitude to connect with your intuition. The High Priestess encourages you to seek wisdom within yourself through solitude, and the Hermit signifies the value of self-reflection.'\n" +
                "2,10,'Unexpected opportunities that resonate with your intuition. The High Priestess encourages you to trust your gut feelings as situations unfold, and the Wheel of Fortune signifies the need to be open to new possibilities that align with your inner wisdom.'\n" +
                "2,11,'Following your inner sense of justice and fairness. The High Priestess encourages you to act with integrity based on your intuition, and Justice highlights the importance of making ethical decisions.'\n" +
                "2,12,'Considering alternative perspectives to gain deeper insights from your intuition. The High Priestess encourages you to explore different viewpoints to enrich your inner wisdom, and the Hanged Man signifies the value of looking at things from a different angle.'\n" +
                "2,13,'Letting go of outdated beliefs or limitations that hinder your intuition. The High Priestess encourages you to trust your inner wisdom and shed anything that blocks it, and Death signifies the need to release the old to make way for a stronger intuition.'\n" +
                "2,14,'Balancing your intuition with logic and reason for sound decision-making. Don`t rely solely on gut feelings or cold logic. Combine them for well-rounded choices.'\n" +
                "2,15,'Beware of negative influences or illusions that cloud your intuition. The High Priestess encourages you to be discerning and trust your gut feelings, and the Devil highlights the importance of avoiding deception and staying true to your inner wisdom.'\n" +
                "2,16,'Sudden disruptions that force you to rely on your intuition. The High Priestess encourages you to trust your gut feelings as you navigate unexpected changes, and the Tower signifies the need to adapt based on your inner wisdom.'\n" +
                "2,17,'Maintaining hope and faith based on your intuition, even amidst uncertainties. The High Priestess encourages you to trust your inner wisdom even when the future seems unclear, and the Star signifies the potential for positive outcomes.'\n" +
                "2,18,'Ignoring your intuition or difficulty trusting your gut feeling. The High Priestess encourages trusting your intuition, and the Moon highlights illusion. This week, be wary of ignoring your inner voice due to fear or uncertainty caused by the Moon`s influence.'\n" +
                "2,19,'The High Priestess represents the journey towards self-discovery, and The Sun represents the moment of enlightenment that comes after the seeker has successfully navigated the introspective journey.'\n" +
                "2,20,'Trust your gut feeling, use your knowledge, and be open to letting go of limiting beliefs that might be hindering your clarity. By following your inner wisdom, you can make choices that lead to personal growth and a deeper sense of purpose.'\n" +
                "2,21,'A feeling of wholeness and fulfillment through following your intuition and inner wisdom. The High Priestess signifies living in alignment with your inner guidance, and the World signifies a sense of completion and living your purpose.'\n" +
                "3,4,'Balancing nurturing and leadership qualities. The Empress encourages nurturing and compassion, while the Emperor signifies structure and providing for others. This pair suggests finding a balance between these qualities.'\n" +
                "3,5,'Teaching with compassion and nurturing a sense of community. The Empress emphasizes nurturing and caring for others, and the Hierophant signifies the act of teaching or learning within a supportive environment.'\n" +
                "3,6,'A week of love, nurturing existing relationships, and fostering new connections. The Empress highlights nurturing love and connection, and the Lovers signify the importance of genuine bonds.'\n" +
                "3,7,'Pursuing your goals with passion and care for yourself and others. The Empress emphasizes compassion and nurturing, while the Chariot signifies determination and focus. This pair suggests combining these qualities to achieve your aspirations.'\n" +
                "3,8,'Finding inner strength through nurturing yourself and others. The Empress highlights nurturing qualities, and Strength signifies the inner resources that come from compassion and self-care.'\n" +
                "3,9,'Taking time for self-care and introspection to replenish your nurturing energy. The Empress signifies the importance of self-care, and the Hermit highlights the value of solitude for rejuvenation.'\n" +
                "3,10,'Unexpected opportunities for nurturing projects, creativity, or relationships. The Empress highlights nurturing potential, and the Wheel of Fortune signifies the arrival of unforeseen chances to express these qualities.'\n" +
                "3,11,'A situation requiring fairness and care. The Empress encourages compassionate solutions and fostering balance, and Justice signifies acting with integrity.'\n" +
                "3,12,'Considering alternative ways to nurture and show compassion. The Empress emphasizes nurturing qualities, and the Hanged Man encourages looking at situations from a different angle to find new ways to care for yourself and others.'\n" +
                "3,13,'Letting go of unhealthy attachments or nurturing projects that no longer serve you. The Empress signifies nurturing qualities, and Death highlights the need to release what no longer brings growth or fulfillment.'\n" +
                "3,14,'Finding a healthy balance between nurturing yourself and others. Prioritize self-care while still being supportive of loved ones.'\n" +
                "3,15,'Beware of smothering relationships or neglecting your own needs due to possessiveness. The Empress encourages healthy nurturing, and the Devil highlights the dangers of attachment and neglecting boundaries.'\n" +
                "3,16,'Sudden disruptions that may impact your nurturing projects or relationships. The Empress signifies nurturing qualities, and the Tower signifies unexpected change. This pair suggests adapting your nurturing approach in the face of disruption.'\n" +
                "3,17,'Maintaining hope and optimism for your creative endeavors or relationships. The Empress encourages nurturing qualities, and the Star signifies the potential for growth and fulfillment in these areas.'\n" +
                "3,18,'Deception or hidden truths in emotional matters or creative projects. The Empress signifies nurturing qualities and creativity, and the Moon highlights illusion. This week, there may be hidden agendas or misunderstandings in your relationships or creative endeavors.'\n" +
                "3,19,'Embrace your creativity, express yourself authentically, and nurture your passions. Your positive energy and nurturing spirit will lead to abundance, joy, success, and strong relationships. It`s a time to turn your dreams into reality and radiate happiness to those around you.'\n" +
                "3,20,'Reflect on what truly nourishes you and let go of anything hindering your progress. Make balanced choices that nurture your creativity and lay a solid foundation for a future filled with abundance.'\n" +
                "3,21,'A feeling of accomplishment and fulfillment through nurturing projects or relationships. The Empress signifies the joy of nurturing, and the World signifies a sense of completion and living your purpose.'\n" +
                "4,5,'Taking on a leadership role within a structured learning environment. The Emperor signifies leadership, and the Hierophant highlights teaching or learning within a system or tradition.'\n" +
                "4,6,'Taking a leadership role in your relationships or setting clear boundaries. The Emperor signifies leadership and providing structure, while the Lovers highlight the importance of healthy relationships. This pair suggests taking charge of your relationships in a positive way.'\n" +
                "4,7,'A powerful combination for achieving goals through focused action and strong leadership. The Emperor emphasizes leadership and structure, while the Chariot signifies determination and focus. This week is likely to be productive for goal achievement.'\n" +
                "4,8,'Leading with inner strength and determination. The Emperor signifies leadership, and Strength highlights inner resources that will help you persevere in your leadership role.'\n" +
                "4,9,'Taking time for solitude to strategize and plan your leadership approach. The Emperor signifies leadership, and the Hermit highlights the value of introspection and solitude for effective planning.'\n" +
                "4,10,'Unexpected opportunities that require leadership and adaptation. The Emperor signifies leadership, and the Wheel of Fortune signifies change. This pair suggests adapting your leadership style to navigate unforeseen circumstances.'\n" +
                "4,11,'A situation requiring fairness and strong leadership. The Emperor signifies leadership and providing structure, while Justice highlights acting with integrity. This week, you may need to make fair and balanced decisions in a leadership role.'\n" +
                "4,12,'Considering alternative leadership approaches or perspectives. The Emperor signifies leadership, and the Hanged Man encourages looking at situations from a different angle. This week, consider new ways to approach your leadership role.'\n" +
                "4,13,'Letting go of outdated leadership styles or structures that no longer serve you. The Emperor signifies leadership, and Death highlights the need to release what no longer works. This week may involve changes in leadership approach or structure.'\n" +
                "4,14,'Exercising leadership with balance and diplomacy. Strive for cooperation and avoid overly forceful tactics.'\n" +
                "4,15,'Beware of controlling or manipulative leadership tactics. The Emperor signifies leadership, and the Devil highlights the dangers of using power for negative purposes. This week, ensure your leadership approach is ethical and avoids manipulation.'\n" +
                "4,16,'Sudden disruptions that may require a change in leadership style or structure. The Emperor signifies leadership and structure, while the Tower signifies unexpected change. This pair suggests adapting your leadership approach in the face of disruption.'\n" +
                "4,17,'Maintaining a vision and inspiring others towards a brighter future. The Emperor signifies leadership, and the Star signifies hope and inspiration. This week, you can motivate and inspire others through your leadership role.'\n" +
                "4,18,'Deception or unclear authority figures. The Emperor signifies leadership, and the Moon highlights illusion. This week, leadership figures may be unclear or lack transparency in their actions.'\n" +
                "4,19,'Embrace your leadership qualities, establish a clear direction, and approach challenges with a confident and optimistic attitude. Remember to find a balance between structure and enjoyment, appreciating the journey alongside achieving success.'\n" +
                "4,20,'Don`t be afraid to question established structures or your own approach. Lead with fairness and wisdom, and be open to letting go of some control for the greater good. By making well-considered choices, you can establish a strong foundation and pave the way for long-term success.'\n" +
                "4,21,'A sense of accomplishment and fulfillment through achieving goals or building a strong foundation. The Emperor signifies leadership and achieving goals, and the World signifies a feeling of wholeness and living your purpose. This week may culminate in a successful outcome from your leadership efforts'\n" +
                "5,6,'Following tradition or seeking guidance from a teacher in your relationships. The Hierophant signifies learning from established traditions, and the Lovers highlight relationships. This week, consider how traditions or a trusted advisor can guide your relationships.'\n" +
                "5,7,'Following a structured approach to achieve your goals. The Hierophant signifies learning from established systems, and the Chariot highlights determination and focus. This week, a structured approach may be beneficial for achieving your aspirations.'\n" +
                "5,8,'Finding inner strength through learning or teaching. The Hierophant signifies the value of learning and teaching, and Strength highlights the inner resources gained through these experiences. This week, you may find personal growth through learning or teaching.'\n" +
                "5,9,'Don`t be afraid to question traditional structures and find your own truth through solitude and self-reflection. Your personal growth journey can hold valuable lessons for yourself and potentially inspire others.'\n" +
                "5,10,'Unexpected opportunities for learning, teaching, or connecting with a mentor. The Hierophant signifies learning and teaching, and the Wheel of Fortune signifies unforeseen chances. This week, be open to unexpected opportunities related to learning or mentorship.'\n" +
                "5,11,'A situation requiring fairness and following established principles. The Hierophant signifies learning from established systems or traditions, and Justice highlights acting with integrity. This week, consider how established principles can guide your actions towards fairness.'\n" +
                "5,12,'Considering alternative perspectives within a learning environment or tradition. The Hierophant signifies learning from established systems, and the Hanged Man encourages looking at things from a different angle.'\n" +
                "5,13,'The Hierophant signifies established systems or traditions, and Death highlights the need to release what no longer works. This week, consider letting go of outdated approaches to learning or teaching.'\n" +
                "5,14,'Temperance and the Hierophant together suggest a week where finding balance and moderation will be crucial when dealing with traditions, established systems, or seeking guidance. Approach these situations with respect, discernment, and a willingness to compromise while staying true to your own values and intuition.'\n" +
                "5,15,'The Hierophant signifies established systems or traditions, and the Devil highlights the dangers of being overly attached to them. This week, ensure your learning or teaching approach is open-minded and avoids blind adherence to outdated ideas.'\n" +
                "5,16,'Sudden disruptions that may impact your learning environment or relationship with a mentor. The Hierophant signifies learning or teaching within a system, and the Tower signifies unexpected change. This week, be prepared to adapt your learning or teaching approach due to disruptions.'\n" +
                "5,17,'Maintaining hope and faith in your learning journey or the guidance of a mentor. The Hierophant signifies learning and teaching, and the Star signifies the potential for growth and fulfillment. This week, stay optimistic about your learning or teaching experience.'\n" +
                "5,18,'Don`t be afraid to question the status quo and look beneath the surface for hidden truths. By staying alert to potential deception and trusting your inner voice, you can navigate this week with wisdom and clarity.'\n" +
                "5,19,'Embrace traditions, share your positive energy, and approach learning with enthusiasm. This is a time to find happiness and success by building a strong foundation within structures that hold meaning for you.'\n" +
                "5,20,'Seek guidance, but make your own choices based on your values and a deeper understanding of your inner truth. By letting go of outdated beliefs and embracing a growth mindset, you can navigate this week with wisdom and clarity.'\n" +
                "5,21,'The Hierophant signifies learning and teaching, and the World signifies a sense of completion and living your purpose. This week may culminate in a successful learning experience or the completion of a course.'\n" +
                "6,7,'Pursuing love interests with determination or working towards a harmonious relationship. The Lovers highlight love and connection, and the Chariot signifies determination and focus. This week, be dedicated to pursuing a love interest or achieving a harmonious relationship.'\n" +
                "6,8,'Finding inner strength to navigate relationship challenges or express your true feelings. The Lovers highlight relationships, and Strength signifies the inner resources that will help you persevere. This week, you may need inner strength to overcome relationship challenges or express your true feelings.'\n" +
                "6,9,'Taking time for yourself doesn`t diminish your connection with others; it can actually lead to deeper understanding and more fulfilling partnerships. By prioritizing your inner well-being, you can approach your relationships with greater clarity and love.'\n" +
                "6,10,'Unexpected opportunities for love, connection, or resolving relationship issues. The Lovers highlight love and connection, and the Wheel of Fortune signifies unforeseen chances. This week, be open to unexpected opportunities related to love or relationships.'\n" +
                "6,11,'A situation requiring fairness, honesty, and open communication in your relationships. The Lovers highlight healthy connections, and Justice signifies acting with integrity. This week, ensure fairness, honesty, and open communication in your relationships.'\n" +
                "6,12,'Considering alternative perspectives to improve understanding or resolve conflict in your relationships. The Lovers highlight connection, and the Hanged Man encourages looking at things from a different angle. This week, consider your partner`s perspective to improve understanding or resolve conflict.'\n" +
                "6,13,'Letting go of unhealthy relationships or patterns that no longer serve you. The Lovers highlight relationships, and Death signifies the need to release what no longer works. This week, consider letting go of a relationship or unhealthy patterns within a relationship.'\n" +
                "6,14,'Finding a healthy balance and compromise in your relationships. Focus on common ground and understanding each other`s needs.'\n" +
                "6,15,'Beware of jealousy, possessiveness, or manipulation in your relationships. The Lovers highlight healthy connections, and the Devil signifies negative aspects of relationships. This week, avoid jealousy, possessiveness, or manipulation in your relationships.'\n" +
                "6,16,'Sudden disruptions or unexpected changes that may impact your relationships. The Lovers highlight relationships, and the Tower signifies unexpected change. This week, be prepared to adapt your relationships in the face of disruption.'\n" +
                "6,17,'Maintaining hope and faith in your relationships, even amidst challenges. The Lovers highlight connections, and the Star signifies the potential for growth and fulfillment. This week, stay optimistic about the future of your relationship.'\n" +
                "6,18,'Deception, misunderstandings, or hidden feelings in your relationships. The Lovers highlight relationships, and the Moon highlights illusion. This week, there may be misunderstandings, hidden feelings, or deception affecting your relationships.'\n" +
                "6,19,'Embrace the joy, express your love openly, and focus on fostering passion and connection. If you`re single, this is a great time to put yourself out there with confidence and optimism. Let your inner light shine, and enjoy the warmth and happiness that love brings.'\n" +
                "6,20,'Don`t be afraid to honestly evaluate your partnerships and make choices that support your well-being.  Open communication and self-reflection can lead to stronger bonds and a deeper understanding of what true love means to you.'\n" +
                "6,21,'A feeling of accomplishment and fulfillment through a strong and harmonious relationship. The Lovers highlight love and connection, and the World signifies a sense of completion and living your purpose. This week may culminate in a significant milestone in your relationship journey.'\n" +
                "7,8,'Finding inner strength and determination to overcome challenges and achieve your goals. The Chariot signifies determination and focus, and Strength highlights the inner resources that will help you persevere. This week, you may need inner strength to navigate obstacles and stay focused on your goals.'\n" +
                "7,9,'Taking time for focused planning and strategizing to achieve your goals. The Chariot signifies determination and focus, and the Hermit highlights the value of solitude for planning. This week, consider taking time to strategize your approach to achieving your aspirations.'\n" +
                "7,10,'Unexpected opportunities or changes in direction that may impact your goals. The Chariot signifies determination and focus, and the Wheel of Fortune signifies unforeseen circumstances. Be prepared to adapt your goals or approach due to unexpected developments.'\n" +
                "7,11,'A situation requiring fairness and balanced action as you pursue your goals. The Chariot signifies determination and focus, and Justice highlights acting with integrity. This week, ensure your actions towards your goals are fair and ethical.'\n" +
                "7,12,'Considering alternative approaches or perspectives to achieve your goals. The Chariot signifies determination and focus, and the Hanged Man encourages looking at things from a different angle. This week, consider alternative strategies or approaches to reach your goals.'\n" +
                "7,13,'Letting go of outdated goals or approaches that no longer serve you. The Chariot signifies determination and focus, and Death highlights the need to release what no longer works. This week, consider letting go of ineffective goals or approaches and setting new intentions.'\n" +
                "7,14,'Balancing your determination with flexibility and adaptability. Stay focused on your goals but be open to adjusting your approach if needed.'\n" +
                "7,15,'Beware of impulsiveness, overambition, or using unethical means to achieve your goals. The Chariot signifies determination and focus, and the Devil highlights negative aspects of ambition. This week, ensure your pursuit of goals is ethical and avoids manipulation.'\n" +
                "7,16,'Sudden disruptions or unexpected challenges that may derail your progress. The Chariot signifies determination and focus, and the Tower signifies unexpected change. This week, be prepared to adapt your approach due to sudden disruptions.'\n" +
                "7,17,'Maintaining hope and faith in your goals, even amidst challenges. The Chariot signifies determination and focus, and the Star signifies the potential for achieving your goals. This week, stay optimistic about your progress, even if there are obstacles.'\n" +
                "7,18,'Lack of clarity or uncertainty about your goals or direction. The Chariot signifies determination and focus, and the Moon highlights illusion. This week, you might feel unclear about your goals or the best course of action due to the Moon`s influence.'\n" +
                "7,19,'Chariot and the Sun together suggest a very promising week for taking action, pursuing your goals, and achieving success.  Embrace your inner strength, take charge with confidence, and approach challenges with optimism.'\n" +
                "7,20,'Don`t rush into things; combine your drive with discernment to make wise choices.  By reflecting on your goals, motivations, and potential paths forward, you can take charge with confidence and navigate any challenges with clarity and wisdom.'\n" +
                "7,21,'A sense of accomplishment and fulfillment through achieving a significant goal. The Chariot signifies determination and focus, and the World signifies a sense of completion and living your purpose. This week may culminate in a significant milestone towards your goals.'\n" +
                "8,9,'Finding inner strength through introspection and solitude. The Hermit signifies introspection and solitude, and Strength highlights inner resources. This week, solitude can be a source of strength as you face challenges.'\n" +
                "8,10,'Unexpected opportunities to utilize your inner strength. The Wheel of Fortune signifies unforeseen circumstances, and Strength highlights inner resources. This week, unexpected situations may require you to tap into your inner strength.'\n" +
                "8,11,'Standing up for what`s right and acting with integrity requires inner strength. The Strength card highlights inner resources, and Justice signifies acting with fairness. This week, you may need inner strength to defend your values or act fairly in a challenging situation.'\n" +
                "8,12,'Considering alternative perspectives can build inner strength. The Hanged Man encourages looking at things from a different angle, and Strength highlights inner resources. This week, consider alternative viewpoints to gain a new perspective and build your inner strength.'\n" +
                "8,13,'Letting go of outdated beliefs or limitations that hinder your inner strength. Strength highlights inner resources, and Death signifies the need to release what no longer works. This week, consider letting go of negativity or limiting beliefs to build your inner strength.'\n" +
                "8,14,'Balancing your inner strength with compassion and understanding. Use your strength wisely and consider the feelings of others.'\n" +
                "8,15,'Beware of negative emotions or destructive behavior that can drain your inner strength. The Devil highlights negative aspects of human nature, and Strength highlights inner resources. This week, avoid negativity and destructive behaviors to maintain your inner strength.'\n" +
                "8,16,'Sudden disruptions can challenge your inner strength. The Tower signifies unexpected change, and Strength highlights inner resources. This week, be prepared to draw on your inner strength to navigate sudden disruptions.'\n" +
                "8,17,'Maintaining hope and faith, even amidst challenges, builds inner strength. The Star signifies the potential for positive outcomes, and Strength highlights inner resources. This week, stay optimistic, and your inner strength will grow.'\n" +
                "8,18,'Fear or hidden anxieties draining your inner strength. The Strength card highlights inner resources, and the Moon highlights fear. This week, hidden fears or anxieties may be draining your inner strength.'\n" +
                "8,19,'You have the resources within you to overcome any challenges and achieve your goals with grace and compassion.  This week, success will be met with joy and inner peace, making it a truly fulfilling time.'\n" +
                "8,20,'Trust your intuition, make wise decisions based on self-reflection, and remember to approach situations with compassion and inner peace. By embracing your inner strength, you can navigate this week with confidence and emerge stronger.'\n" +
                "8,21,'Strength highlights inner resources, and the World signifies a sense of completion and living your purpose. This week, overcoming challenges with inner strength can lead to a feeling of accomplishment.'\n" +
                "9,10,'A time for introspection and solitude before responding to unexpected situations. The Wheel of Fortune signifies unforeseen circumstances, and the Hermit highlights introspection and solitude. This week, unexpected events may arise. Take time alone to reflect before taking action.'\n" +
                "9,11,'Taking time for self-reflection to ensure your actions are fair and ethical. The Hermit highlights introspection and solitude, and Justice signifies acting with integrity. This week, consider spending time alone to reflect on your actions and ensure they are fair and ethical.'\n" +
                "9,12,'Considering alternative perspectives through solitude and introspection. The Hanged Man encourages looking at things from a different angle, and the Hermit highlights introspection and solitude. This week, solitude can be a catalyst for considering alternative viewpoints and gaining new perspectives.'\n" +
                "9,13,'A time for letting go of outdated beliefs or habits that no longer serve you. The Hermit highlights introspection and solitude, and Death signifies the need to release what no longer works. This week, consider spending time alone to reflect and identify what you need to let go of to move forward.'\n" +
                "9,14,'Balancing solitude with social connection for well-being. Make time for reflection, but don`t isolate yourself completely.'\n" +
                "9,15,'Beware of isolation or emotional withdrawal that can be detrimental. The Devil highlights negative aspects of solitude, and the Hermit highlights introspection and solitude. This week, ensure your need for solitude isn`t leading to isolation or emotional withdrawal.'\n" +
                "9,16,'Sudden disruptions may require time for reflection and adjustment. The Tower signifies unexpected change, and the Hermit highlights introspection and solitude. This week, unexpected events may occur. Take time alone to process the changes and adjust your plans.'\n" +
                "9,17,'Maintaining hope and faith in your goals or path, even during times of solitude. The Star signifies the potential for positive outcomes, and the Hermit highlights introspection and solitude. This week, solitude can be a time for reflection and renewed faith in your goals or path.'\n" +
                "9,18,'Isolation due to fear or emotional withdrawal. The Hermit highlights introspection and solitude, and the Moon highlights fear. This week,  isolation due to fear or emotional withdrawal may be amplified by the Moon`s influence.'\n" +
                "9,19,'Hermit and the Sun together suggest a week where introspection and solitude can be powerful tools for finding joy and fulfillment. Embrace this time for self-discovery and inner peace. The positive energy and wisdom you gain from solitude can radiate outward and inspire you and those around you.'\n" +
                "9,20,'aking time for solitude can provide the clarity you need to make important decisions and stand up for what you believe in.  Trust your inner wisdom and discernment to navigate situations and make choices that align with your authentic self.'\n" +
                "9,21,'A sense of accomplishment and fulfillment through self-discovery or a period of solitude. The Hermit highlights introspection and solitude, and the World signifies a sense of completion and living your purpose. This week, solitude may lead to self-discovery or a feeling of fulfillment.'\n" +
                "10,11,'Unexpected situations that require fairness and balanced action. The Wheel of Fortune signifies unforeseen circumstances, and Justice highlights acting with integrity. This week, unexpected events may necessitate fair and ethical responses.'\n" +
                "10,12,'Unexpected opportunities to consider alternative perspectives. The Hanged Man encourages looking at things from a different angle, and the Wheel of Fortune signifies unforeseen circumstances. This week, unexpected situations may prompt you to consider alternative viewpoints.'\n" +
                "10,13,'Unexpected endings or sudden changes that require letting go. The Wheel of Fortune signifies unforeseen circumstances, and Death highlights the need to release what no longer works. This week, unexpected situations may necessitate letting go of something.'\n" +
                "10,14,'Adapting to unexpected circumstances with grace and resilience. Unexpected events may occur. Stay calm, adaptable, and maintain your balance.'\n" +
                "10,15,'Beware of being overly attached to plans or expectations, as unexpected changes may occur. The Devil highlights attachment, and the Wheel of Fortune signifies unforeseen circumstances. This week, be flexible and adaptable, as unexpected events may disrupt your plans.'\n" +
                "10,16,'Sudden disruptions and unexpected turns of events. The Wheel of Fortune and the Tower both signify sudden change. This week, brace yourself for significant disruptions that may require adjustments.'\n" +
                "10,17,'Maintaining hope and faith, even amidst unexpected changes. The Star signifies the potential for positive outcomes, and the Wheel of Fortune signifies unforeseen circumstances. This week, unexpected events may occur, but stay optimistic about the future.'\n" +
                "10,18,'Unexpected events or sudden changes shrouded in uncertainty. The Wheel of Fortune signifies unforeseen circumstances, and the Moon highlights illusion. This week, expect unexpected events, but the details may be unclear due to the Moon`s influence.'\n" +
                "10,19,'Embrace the inevitable changes with optimism and a positive attitude.  Unexpected turns can lead to new beginnings filled with joy and success. Let your inner light shine and navigate this week with confidence, finding the joy in the unexpected journey.'\n" +
                "10,20,'Embrace your inner wisdom and make choices based on past experiences and your values. Taking responsibility for your actions and discerning opportunities within change can empower you to navigate this week with growth and a sense of control over your destiny.'\n" +
                "10,21,'The Wheel of Fortune signifies unforeseen circumstances, and the World signifies a sense of completion and living your purpose. This week, unexpected developments may lead to a positive outcome or a feeling of accomplishment.'\n" +
                "11,12,'Considering alternative perspectives to ensure fairness and balance. The Hanged Man encourages looking at things from a different angle, and Justice highlights acting with fairness. This week, consider alternative viewpoints to ensure your decisions are fair and balanced.'\n" +
                "11,13,'Letting go of situations or relationships that are no longer fair or just. The Death card highlights the need to release what no longer works, and Justice signifies fairness. This week, consider letting go of unfair situations or relationships that are no longer serving you.'\n" +
                "11,14,'Finding a balance between fairness and mercy when making judgments. Consider both justice and compassion in your decisions.'\n" +
                "11,15,'Beware of deception, manipulation, or unfair treatment. The Devil highlights negative aspects of human nature, and Justice signifies acting with fairness. This week, be cautious of situations or people who may be acting unfairly or deceptively.'\n" +
                "11,16,'Sudden disruptions or revelations of injustice that may require correction. The Tower signifies unexpected change, and Justice highlights fairness. This week, unexpected events may expose injustice, prompting the need for correction.'\n" +
                "11,17,'Maintaining hope and faith in achieving a just outcome. The Star signifies the potential for positive outcomes, and Justice highlights fairness. This week, stay optimistic about the possibility of a fair and just resolution.'\n" +
                "11,18,'Deception, unfairness, or a lack of clarity in legal matters or judgments. The Moon highlights illusion, and Justice signifies fairness. This week, be cautious of deception or a lack of transparency in legal matters or situations requiring fairness.'\n" +
                "11,19,'Approach situations with fairness, honesty, and integrity.  Open communication and balanced actions will lead to positive outcomes and a sense of harmony. Embrace the joy of seeing your efforts rewarded and inspire others with your fair and positive approach.'\n" +
                "11,20,'Focus on fairness, accountability, and making decisions that align with your sense of right and wrong.  By holding yourself and others accountable for unfairness, you can navigate situations and make choices that promote a sense of justice and balance.'\n" +
                "11,21,'The World signifies a sense of completion and living your purpose, and Justice highlights fairness. This week, achieving a just outcome may lead to a feeling of accomplishment and alignment with your purpose.'\n" +
                "12,13,'Letting go of outdated perspectives or beliefs that are no longer serving you. The Death card highlights the need to release what no longer works, and the Hanged Man encourages looking at things from a different angle. This week, consider letting go of limiting perspectives or beliefs to embrace new possibilities.'\n" +
                "12,14,'Finding balance by considering alternative perspectives. Don`t get stuck in your own viewpoint. Consider seeing things from a different angle.'\n" +
                "12,15,'Beware of stubbornness, resistance to change, or clinging to outdated perspectives. The Devil highlights negative aspects of human nature, and the Hanged Man encourages looking at things from a different angle. This week, avoid clinging to negativity or resistance to change. Be open to new perspectives.'\n" +
                "12,16,'Sudden disruptions may prompt you to adopt a new perspective. The Tower signifies unexpected change, and the Hanged Man encourages looking at things from a different angle. This week, unexpected events may necessitate adopting a new perspective.'\n" +
                "12,17,'Maintaining hope and faith, even amidst challenges, can lead to new perspectives and breakthroughs. The Star signifies the potential for positive outcomes, and the Hanged Man encourages looking at things from a different angle. This week, stay optimistic. New perspectives and breakthroughs may emerge even during challenges.'\n" +
                "12,18,'Difficulty considering new perspectives due to fear or clinging to illusions. The Hanged Man encourages looking at things from a different angle, and the Moon highlights illusion. This week, fear or clinging to illusions may make it difficult to consider alternative viewpoints.'\n" +
                "12,19,'Don`t be afraid to surrender control, accept the present moment, and explore new ideas. Inner peace and a shift in perspective can lead to unexpected joy, success, and a deeper sense of fulfillment.'\n" +
                "12,20,'Taking time to re-evaluate your priorities and limitations can empower you to let go of what no longer serves you and make wise choices based on a new perspective.  By surrendering to the present and letting go, you can create space for positive change and a fresh start.'\n" +
                "12,21,'The World signifies a sense of completion and living your purpose, and the Hanged Man encourages looking at things from a different angle. This week, achieving a new perspective or way of approaching a situation can lead to a feeling of accomplishment.'\n" +
                "13,14,'Letting go of negativity or unhealthy habits while embracing moderation. Consider letting go of negativity or overindulgence, finding a healthier middle ground.'\n" +
                "13,15,'Letting go of negativity, addictions, or unhealthy attachments. The Devil highlights negative aspects of human nature, and Death signifies the need to release what no longer works. This week, prioritize letting go of negativity, addictions, or unhealthy attachments that are hindering your progress.'\n" +
                "13,16,'Sudden disruptions or endings that may be a catalyst for transformation. The Tower signifies unexpected change, and Death highlights the need to release what no longer works. This week, unexpected events may lead to endings, but these can also be opportunities for positive transformation.'\n" +
                "13,17,'Maintaining hope and faith, even amidst endings, as new beginnings are on the horizon. The Star signifies the potential for positive outcomes, and Death highlights the need to release what no longer works. This week, even amidst endings, stay optimistic about new beginnings and the potential for growth.'\n" +
                "13,18,'Letting go of illusions or emotional attachments that no longer serve you. The Death card highlights the need to release what no longer works, and the Moon highlights illusion. This week, consider letting go of illusions or unhealthy emotional attachments that are hindering your progress.'\n" +
                "13,19,'Death and the Sun together suggest a week of transformation and change.  While endings might occur, they are likely to lead to positive new beginnings filled with joy and success. Embrace this period of transition, let go of what no longer serves you, and find the joy in the process of growth and renewal.'\n" +
                "13,20,'Death and Judgement together suggest a week where transformation and endings might occur. Embrace introspection and use this time for self-reflection.  By letting go of what no longer serves you and making clear choices based on your newfound clarity, you can pave the way for positive new beginnings and a brighter future.'\n" +
                "13,21,'A sense of accomplishment and fulfillment through a significant ending or transformation. The World signifies a sense of completion and living your purpose, and Death highlights the need to release what no longer works. This week, a significant ending or transformation may lead to a feeling of accomplishment and alignment with your purpose.'\n" +
                "14,15,'Finding balance and moderation to avoid temptation or overindulgence. Be mindful of temptations and avoid negativity. Find a balanced approach.'\n" +
                "14,16,'Adapting to sudden disruptions with a balanced and steady approach. Unexpected events may occur. Stay calm and adapt with a balanced approach.'\n" +
                "14,17,'Finding balance between hope and pragmatism for positive outcomes. Don`t be overly optimistic, but maintain hope while taking practical steps.'\n" +
                "14,18,'Despite uncertainty or hidden truths, use your intuition and discernment to navigate challenges and find inner peace. Avoid jumping to conclusions or making decisions based on fear or incomplete information. '\n" +
                "14,19,'Temperance and the Sun together suggest a very positive week. Finding balance and moderation in your life will open doors to happiness, success, and a sense of fulfillment. Embrace the joy and share it with others while maintaining your inner peace and healthy habits.'\n" +
                "14,20,'Approach situations with objectivity, a willingness to compromise, and a sense of acceptance. By finding peace within yourself, you can navigate challenges and make sound judgments that lead to positive outcomes.'\n" +
                "14,21,'A sense of accomplishment and fulfillment through achieving balance and harmony. This week, achieving a sense of balance and harmony in your life can lead to a feeling of accomplishment and fulfillment.'\n" +
                "15,16,'Sudden disruptions due to unhealthy attachments or negative behavior. The Tower signifies unexpected change, and the Devil highlights attachment and temptation. This week, unexpected events may be a consequence of unhealthy attachments or negative behavior.'\n" +
                "15,17,'Maintaining hope and faith, even amidst temptation, for positive change. The Star signifies the potential for positive outcomes, and the Devil highlights temptation and illusion. This week, even amidst temptation, stay optimistic about the potential for positive change.'\n" +
                "15,18,'Deception or manipulation related to temptation or addiction. The Devil highlights temptation and attachment, and the Moon highlights illusion. This week, be wary of deception or manipulation related to temptations or addictions.'\n" +
                "15,19,'Embrace your inner strength, prioritize self-awareness, and actively seek out experiences and choices that bring genuine happiness. By resisting the allure of the Devil`s temptations, you can navigate this week with a focus on long-term fulfillment and a sense of inner joy.'\n" +
                "15,20,'Use this as an opportunity for self-reflection and judgement.  By recognizing unhealthy influences and limitations, and making clear choices based on your values, you can break free from negative patterns and embrace a more authentic and fulfilling path.'\n" +
                "15,21,'The World signifies a sense of completion and living your purpose, and the Devil highlights attachment and temptation. This week, overcoming negative attachments or limitations can lead to a feeling of accomplishment and alignment with your purpose.'\n" +
                "16,17,'Maintaining hope and faith, even amidst sudden disruptions, for positive outcomes. The Star signifies the potential for positive outcomes, and the Tower signifies unforeseen changes. This week, even amidst unexpected events, stay optimistic about the potential for positive change.'\n" +
                "16,18,'Sudden disruptions or revelations due to hidden truths or illusions coming to light. The Tower signifies unexpected change, and the Moon highlights illusion. This week, unexpected events may be caused by hidden truths or illusions coming to light.'\n" +
                "16,19,'While these changes might be unsettling initially, the Sun`s influence reminds you that they could be opportunities for positive growth and a brighter future.  Embrace your inner strength, stay optimistic, and focus on rebuilding with a sense of hope and the potential for joy in the journey ahead.'\n" +
                "16,20,'Embrace this as an opportunity for introspection and self-reflection.  By taking responsibility, letting go of what no longer serves you, and making clear choices aligned with your values, you can navigate this disruption and rebuild your life on a stronger foundation.'\n" +
                "16,21,'The World signifies a sense of completion and living your purpose, and the Tower signifies unexpected change. This week, unexpected events may disrupt your current path but lead you to a new sense of purpose or direction.'\n" +
                "17,18,'Maintaining hope and faith, even amidst uncertainty, for positive outcomes. The Star signifies hope and positive potential, and the Moon highlights illusion. This week, even amidst uncertainty caused by the Moon, hold onto hope for positive outcomes.'\n" +
                "17,19,'Trust your intuition, embrace the journey, and take inspired action towards your goals. With a positive attitude and unwavering belief in yourself, you can achieve success and experience the joy of manifesting your desires.'\n" +
                "17,20,'Embrace this time for reflection, trust your intuition, and make decisions that align with your highest aspirations and sense of purpose.  With newfound clarity and confidence, you can confidently take inspired action towards a brighter future.'\n" +
                "17,21,'A sense of accomplishment and fulfillment through achieving your goals or aspirations. The World signifies a sense of completion and living your purpose, and the Star signifies hope and positive potential. This week, achieving your goals or aspirations can lead to a feeling of accomplishment and fulfillment.'\n" +
                "18,19,'Embrace your intuition while taking action, and strive to find joy and fulfillment despite emotional challenges.  By integrating these two powerful forces, you can make well-rounded decisions and achieve success this week.'\n" +
                "18,20,'Delve deeper into your emotional landscape, acknowledge your intuition, but also strive for clear-headed decision making. By embracing emotional growth and self-awareness, you can gain clarity and make choices that align with your true desires and well-being.'\n" +
                "18,21,'A sense of accomplishment may be clouded by uncertainty or hidden truths. The World signifies completion and living your purpose, and the Moon highlights illusion. This week, a sense of accomplishment may be clouded by lingering uncertainty or hidden truths.'\n" +
                "19,20,'Embrace this time for introspection, identify your true desires, and make clear choices that align with your values.  With newfound clarity, confidence, and a positive outlook, you can achieve success and experience the joy of fulfilling your true potential.'\n" +
                "19,21,'Celebrate your achievements, embrace new beginnings, and share your joy with others. With your radiant energy and sense of purpose, you can inspire and connect with those around you. This is a time to enjoy the fruits of your labor and embrace the possibilities that lie ahead.'\n" +
                "20,21,'By reflecting on your experiences and making wise choices, you can release what no longer serves you and embrace the transformation that awaits. Celebrate your achievements and approach the future with a sense of openness and possibility.'"
    }
}