package com.example.tarotapp.db.cards.files

class WorkReading {
    companion object {
        public var workReading = "0,1,'This combination suggests embarking on a new career path that utilizes your skills and talents. You might be starting a business, taking on a new project that allows you to showcase your abilities, or applying your creativity to solve problems at work.'\n" +
                "0,2,'Following your intuition and inner wisdom can lead you down an unexpected but fulfilling path in your career. This pairing might signify that a new opportunity arises that sparks your curiosity and feels right on a gut level, even if it lacks complete information.'\n" +
                "0,3,'This pairing signifies finding joy and creativity in your work. You might be starting a new role that allows you to express yourself and nurture your talents. The Fool`s influence can also suggest bringing a positive and nurturing energy to your current work environment.'\n" +
                "0,4,'Taking a structured and ambitious approach to a new career path is highlighted here. This pairing suggests that you`re determined to achieve your goals and are willing to put in the hard work required for success.'\n" +
                "0,5,'This combination can represent taking a traditional approach to your career, especially if you`re new to a field. The Hierophant suggests learning from experienced mentors and following established procedures for success.'\n" +
                "0,6,'A tough decision at work might require you to weigh a secure option against a more exciting but risky path. This pairing signifies a crossroads in your career, where you might have to choose between following your passion and a more practical choice.'\n" +
                "0,7,'This combination signifies taking control and actively pursuing your career goals. The Fool`s influence here can urge you to avoid getting bogged down in micromanaging or overly rigid control.'\n" +
                "0,8,'Approaching challenges with courage and inner strength can help you overcome obstacles in your career. This pairing suggests you`ll have the willpower and determination to navigate difficult situations at work.'\n" +
                "0,9,'Taking time for introspection and solitude can be valuable for gaining clarity on your career path. This pairing might suggest the need for a period of reflection to assess your goals and priorities before taking action.'\n" +
                "0,10,'Change and unexpected events are inevitable in the workplace. This pairing suggests that you might be about to experience a shift in your career path, possibly due to external factors beyond your control.'\n" +
                "0,11,'Fairness, integrity, and ethical conduct are important aspects of a fulfilling career. This pairing can signify a situation where you need to stand up for what`s right, even if it`s unpopular.'\n" +
                "0,12,'Taking a different perspective or a temporary pause in your career path can be beneficial for considering new options. This pairing suggests that you might be at a crossroads, needing to re-evaluate your priorities before taking the next step. '\n" +
                "0,13,'Death doesn`t always signify literal endings; it can represent transformation and the letting go of the old to make way for the new. In this context, this pairing suggests a significant change in your career path, possibly ending an old job or a complete shift in direction.'\n" +
                "0,14,'Finding balance and moderation is key to a successful and fulfilling career. This pairing suggests that you might need to find a middle ground between competing priorities or opposing viewpoints in the workplace'\n" +
                "0,15,'The Devil can represent temptation, materialism, or unhealthy attachments to work or status. This pairing suggests that you might be facing a situation where you need to re-evaluate your priorities and ensure your work aligns with your values.'\n" +
                "0,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that you might experience an unexpected setback or challenge at work. The Fool`s influence encourages you to remain adaptable and see this disruption as an opportunity for positive change.'\n" +
                "0,17,'Maintaining hope and optimism can help you navigate difficult times at work. This pairing suggests that even if you face challenges, you have the inner strength and resources to overcome them.'\n" +
                "0,18,'This pairing is a very positive sign for your career. It signifies success, achievement, and recognition for your efforts. The Fool`s influence suggests that you`ll be able to approach your work with joy and enthusiasm, leading to fulfilling results.'\n" +
                "0,19,'Hidden fears or lack of clarity might be present.  However, this pairing can also encourage embracing intuition, creative problem-solving, and trusting your gut feeling to navigate the unknown and find a fulfilling path.'\n" +
                "0,20,'A period of self-reflection and reevaluation of your career path might be necessary. This pairing suggests that you`ll be called upon to assess your progress and make adjustments if needed.'\n" +
                "0,21,'This pairing signifies achieving a sense of completion and fulfillment in your career. You might be reaching a major milestone or realizing a long-held dream. The Fool`s presence reminds you to celebrate your achievements and embrace new beginnings and opportunities that might arise.'\n" +
                "1,2,'This pairing suggests that by combining your skills and knowledge with your intuition, you can turn ideas into reality. Trust your gut feeling while also applying your expertise to solve problems creatively in the workplace.'\n" +
                "1,3,'This combination signifies using your skills and talents to cultivate a thriving and productive work environment. You might be in a role that allows you to nurture creativity in yourself and your colleagues, leading to abundance and success.'\n" +
                "1,4,'The Magician`s resourcefulness combined with the Emperor`s strategic mind is a powerful combination. This pairing suggests that you`ll be able to take a structured and results-oriented approach to your work, using your skills to build a successful career.'\n" +
                "1,5,'While The Magician represents innovation and fresh ideas, The Hierophant signifies tradition and established practices. This pairing suggests that you might be successful by applying your skills and knowledge within a structured work environment.'\n" +
                "1,6,'Using your skills to navigate a difficult choice at work can be crucial. This pairing suggests that you`ll need to weigh the pros and cons of different options while staying true to your values and goals.'\n" +
                "1,7,'Taking control and directing your career path with focused action is highlighted here. The Magician`s influence, combined with the Chariot`s drive, suggests that you`ll be able to use your skills and determination to overcome obstacles and achieve your work goals.'\n" +
                "1,8,'This pairing suggests that your skills and inner strength can help you overcome challenges at work. You have the willpower and determination to navigate difficult situations and find solutions using your expertise.'\n" +
                "1,9,'Taking time for introspection and solitude can be valuable for developing your skills and knowledge. This pairing might suggest a need to learn a new skill or refine an existing one through dedicated practice.'\n" +
                "1,10,'Change and unexpected events are inevitable in the workplace. This pairing suggests that you`ll need to be adaptable and resourceful to navigate unexpected shifts in your career path.'\n" +
                "1,11,'This pairing signifies using your skills and knowledge in a way that is fair, ethical, and promotes justice. You might be in a role where you advocate for what`s right, even if it`s unpopular.'\n" +
                "1,12,'Taking a different perspective or a temporary pause in your career path can be beneficial for finding new and innovative solutions. This pairing suggests that by approaching a problem from a different angle, you can use your skills and creativity to develop a strategic solution.'\n" +
                "1,13,'Death doesn`t always signify literal endings; it can represent transformation. This pairing suggests that your skills and knowledge might need to adapt or evolve due to a significant change in your career path.'\n" +
                "1,14,'Finding balance and working effectively with others is key to success in many workplaces. This pairing suggests that you might need to use your skills and knowledge while also compromising and collaborating with colleagues.'\n" +
                "1,15,'The Devil can represent temptation, materialism, or unhealthy attachments to work or status. This pairing suggests that you might be in a situation where your skills are being used for unethical purposes or in a way that conflicts with your values.'\n" +
                "1,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that you might experience an unexpected setback or challenge at work. The Magician encourages you to remain resourceful and use your skills to find creative solutions and rebuild after the disruption.'\n" +
                "1,17,'Maintaining hope and optimism can help you navigate difficult times at work. This pairing, with The Star`s influence, suggests that even if you face challenges, you have the skills and resources to overcome them.'\n" +
                "1,18,'The Moon signifies hidden fears, uncertainties, and lack of clarity. This pairing suggests that you might face unforeseen obstacles or challenges at work. The Magician encourages you to tap into your intuition and use your skills to navigate these uncertainties creatively.'\n" +
                "1,19,'This pairing is a very positive sign for your career. It signifies success, achievement, and recognition for your skills and expertise. The Magician`s influence suggests that you`ll be able to use your talents effectively and achieve your goals, leading to well-deserved recognition.'\n" +
                "1,20,'A period of self-reflection and reevaluation of your skills and approach to work might be necessary. This pairing suggests that you might need to assess your strengths and weaknesses and identify areas for improvement.'\n" +
                "1,21,'This pairing signifies achieving a sense of mastery and completion with your current skillset. You might be reaching a major milestone or realizing a long-held dream of using your skills to create something significant.'\n" +
                "2,3,'This pairing suggests that by trusting your intuition and inner wisdom, you can create a fulfilling and successful career path. You might be drawn to roles that allow you to nurture your talents and create something beautiful or meaningful.'\n" +
                "2,4,'This combination signifies using your intuition alongside strategic planning to build a solid foundation for your career. While The Emperor emphasizes structure and organization, The High Priestess reminds you to trust your gut feeling.'\n" +
                "2,5,'While The Hierophant represents tradition and established practices, The High Priestess signifies intuition and inner wisdom. This pairing suggests that you might find success by combining your intuition with existing systems in your workplace.'\n" +
                "2,6,'A tough decision at work might require you to weigh logic against your gut feeling. This pairing signifies that trusting your intuition can be the key to making the right choice, especially if it aligns with your long-term goals and a sense of deep fulfillment.'\n" +
                "2,7,'Following your intuition and inner wisdom can help you navigate challenges and achieve your goals at work. This pairing suggests that by trusting your gut and remaining focused, you`ll be able to overcome obstacles and reach your desired destination.'\n" +
                "2,8,'Approaching challenges with courage and inner strength is important. This pairing suggests that by trusting your instincts and intuition, you`ll be able to navigate difficult situations at work and find solutions that resonate with you.'\n" +
                "2,9,'Taking time for introspection and solitude can be valuable for gaining clarity on your career path. This pairing suggests that a period of quiet reflection can help you connect with your inner wisdom and gain valuable insights for your work.'\n" +
                "2,10,'Change and unexpected events are inevitable in the workplace. This pairing suggests that by staying connected to your intuition, you can navigate these changes with more grace and make decisions that align with your inner wisdom.'\n" +
                "2,11,'This pairing signifies that fairness, integrity, and ethical conduct are important aspects of a fulfilling career. The High Priestess suggests that by following your intuition and inner moral compass, you`ll be guided towards making ethical decisions in the workplace, even if they`re unpopular.'\n" +
                "2,12,'Taking a different perspective or a pause in your career path can be beneficial for gaining clarity and insights. This pairing suggests that by stepping away from the usual routine and trusting your inner knowing, you might discover new and intuitive approaches to your work.'\n" +
                "2,13,'Death doesn`t always signify literal endings; it can represent transformation and letting go of the old to make way for the new. This pairing suggests that a significant change in your career path might be on the horizon.'\n" +
                "2,14,'Finding balance and moderation is key to a successful career. This pairing suggests that you might need to use your intuition to navigate a situation with competing priorities or viewpoints.'\n" +
                "2,15,'The Devil can represent temptation, materialism, or unhealthy attachments to work or status. This pairing suggests that you might be facing a situation where your intuition warns you of something misaligned with your values. '\n" +
                "2,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that by staying connected to your intuition, you can navigate unforeseen challenges with more resilience.'\n" +
                "2,17,'Maintaining hope and optimism can help you navigate difficult times at work. This pairing suggests that even if you face challenges, by trusting your intuition and inner wisdom, you`ll find the strength and resources to overcome them.'\n" +
                "2,18,'The Moon signifies hidden fears, uncertainties, and lack of clarity. This pairing suggests that you might be dealing with underlying anxieties or uncertainties about your career path.'\n" +
                "2,19,'This pairing signifies achieving success and fulfillment in your career through following your intuition and inner wisdom. The High Priestess reminds you to trust your gut feeling and pursue work that aligns with your deepest values and brings you joy.'\n" +
                "2,20,'A period of self-reflection and reevaluation of your career path might be necessary. This pairing suggests that you`ll be called upon to assess your progress and make adjustments if needed, all while staying true to your inner wisdom and purpose.'\n" +
                "2,21,'This pairing suggests that by trusting your intuition and inner voice throughout your career journey, you`ve reached a place of deep satisfaction and fulfillment. You might be achieving a major milestone, realizing a long-held dream, or simply feeling a deep sense of purpose and accomplishment in your work.'\n" +
                "3,4,'This pairing signifies creating a stable and successful work environment where growth can flourish. The Empress`s nurturing energy combines with the Emperor`s focus on structure and organization to build a solid foundation for your career or your team.'\n" +
                "3,5,'This combination suggests that you might find success by nurturing and promoting established practices while also fostering innovation in the workplace. You could be a mentor who guides others while also encouraging fresh perspectives and creative approaches.'\n" +
                "3,6,'This pairing suggests that a work decision might involve balancing your passions with practical considerations. The Empress encourages you to pursue work that aligns with your values and brings you a sense of fulfillment, even if it`s not the most traditional or financially secure option.'\n" +
                "3,7,'The Empress`s nurturing energy combines with the Chariot`s drive and determination to help you achieve your work goals. This pairing suggests that you`ll be able to use your creativity and resourcefulness to cultivate a successful and fulfilling career path.'\n" +
                "3,8,'This pairing signifies that your inner strength and resilience will help you overcome challenges at work. The Empress`s nurturing energy can also empower you to support and motivate others in your team.'\n" +
                "3,9,'Taking time for introspection and solitude can be valuable for creative pursuits. This pairing suggests that a period of focused work or reflection can lead to new ideas and innovative solutions in your work. The Empress reminds you to use this time to nurture your creativity and resourcefulness.'\n" +
                "3,10,'Change and unexpected events are inevitable in the workplace. This pairing suggests that by embracing change and adapting to new circumstances, you can cultivate growth and abundance in your career. '\n" +
                "3,11,'Creating a fair, ethical, and collaborative work environment is key to fostering growth and abundance for everyone. This pairing suggests that you might be in a role where you advocate for fair treatment, promote collaboration, and nurture a positive work culture.'\n" +
                "3,12,'Taking a different perspective or a temporary pause in your career path can be beneficial for generating new ideas. This pairing suggests that by stepping back and looking at things from a different angle, you can nurture new approaches and solutions that benefit your work.'\n" +
                "3,13,'Death doesn`t always signify literal endings; it can represent transformation. This pairing suggests that your work environment or role might undergo a significant change. The Empress encourages you to embrace this transformation and cultivate new opportunities for growth and abundance.'\n" +
                "3,14,'Finding balance and working effectively with others is key to creating a successful and positive work environment. This pairing suggests that you might need to find a middle ground between competing priorities or collaborate effectively with colleagues.'\n" +
                "3,15,'The Devil can represent temptation, materialism, or unhealthy attachments to work or status. This pairing suggests that you might face a situation where prioritizing material gain or status conflicts with your values of nurturing and creating something meaningful. '\n" +
                "3,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that your work environment might experience an unexpected setback. The Empress`s nurturing energy can help you rebuild and create new growth after the disruption.'\n" +
                "3,17,'Maintaining hope and optimism can help you navigate difficult times at work. This pairing suggests that even if you face challenges, by fostering a sense of hope and renewal, you can cultivate a thriving and positive work environment.'\n" +
                "3,18,'This pairing suggests a need for patience, intuition, and creative problem-solving to navigate uncertainties and nurture growth in your work environment. Remember, The Moon doesn`t always represent negativity; it can also signify hidden potential waiting to be unveiled.'\n" +
                "3,19,'This is a very positive sign for your career. It signifies success, achievement, and abundance in your work. The Empress`s nurturing energy has led to the creation of a successful and fulfilling work environment. The Sun suggests recognition for your efforts and a sense of joy in your work.'\n" +
                "3,20,'A period of self-reflection and reevaluation of your work environment or role might be necessary. This pairing suggests that you might need to assess your progress and consider adjustments to ensure your work aligns with your values of nurturing and fostering growth.'\n" +
                "3,21,'This pairing signifies achieving a sense of completion and fulfillment in your role, where you`ve successfully nurtured a thriving and productive work environment. The World suggests that you might have reached the pinnacle of your current role and be ready for new challenges. '\n" +
                "4,5,'This pairing signifies strong leadership that upholds established systems and traditions while also being open to innovation. You might be in a leadership role where you maintain a balance between structure and encouraging new ideas.'\n" +
                "4,6,'A tough decision at work might require balancing logic and practicality with empathy and understanding. This pairing suggests that effective leadership involves making tough choices while considering all perspectives and potential consequences.'\n" +
                "4,7,'The Emperor`s focus and organizational skills combine with the Chariot`s drive and determination to achieve goals. This pairing suggests that your leadership will be instrumental in achieving success for your team or project.'\n" +
                "4,8,'This pairing signifies strong leadership that is fair, compassionate, and inspires others. The Emperor`s focus and structure are balanced by Strength`s inner strength and ability to overcome challenges.'\n" +
                "4,9,'Taking time for introspection and solitude can be valuable for effective leadership. This pairing suggests that a period of strategic planning and reflection will benefit your leadership style. The Emperor reminds you to use this time to make sound decisions for your team.'\n" +
                "4,10,'Change and unexpected events are inevitable in the workplace. This pairing suggests that effective leadership involves adapting to change while maintaining a sense of order and structure. The Emperor encourages you to be flexible and find new solutions to navigate unforeseen circumstances.'\n" +
                "4,11,'This pairing signifies leadership that prioritizes fairness, ethics, and equal treatment for all. The Emperor`s focus on structure ensures that decisions are made with a sense of justice and transparency.'\n" +
                "4,12,'Taking a different perspective or a pause in your leadership approach can be beneficial. This pairing suggests that stepping back and considering alternative approaches can lead to more effective solutions.'\n" +
                "4,13,'Death doesn`t always signify literal endings; it can represent transformation. This pairing suggests that there might be a significant change in your leadership role or the overall structure of your work environment. '\n" +
                "4,14,'Finding balance and working effectively with others is key to successful leadership. This pairing suggests that you might need to find a middle ground between competing priorities or viewpoints within your team.'\n" +
                "4,15,'The Devil can represent temptation, manipulation, or prioritizing power over people. This pairing suggests that you might face a situation where someone`s leadership style is unethical or manipulative.'\n" +
                "4,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that your leadership role or the overall structure of your work environment might experience a sudden setback. The Emperor`s focus on structure will be crucial for rebuilding order and stability after the disruption.'\n" +
                "4,17,'This pairing signifies leadership that inspires hope and maintains a positive vision for the future, even in challenging times. The Emperor`s structure provides a foundation for achieving the team`s long-term goals.'\n" +
                "4,18,'The Moon signifies hidden fears, uncertainties, and a lack of clarity. This pairing suggests that you might face unforeseen challenges or a lack of information that hinders your leadership efforts.'\n" +
                "4,19,'This is a very positive sign for your leadership role. It signifies successful leadership that has achieved positive results and earned recognition. The Emperor`s focus and structure have led to a well-organized and productive work environment.'\n" +
                "4,20,'A period of self-reflection and reevaluation of your leadership style might be necessary. This pairing suggests that you might need to assess your strengths and weaknesses as a leader and identify areas for improvement.'\n" +
                "4,21,'This pairing signifies achieving a sense of completion and fulfillment in your leadership role. You might have successfully built a strong and productive team or achieved a major organizational goal. The World suggests that your leadership skills have brought structure and success to your work environment.'\n" +
                "5,6,'This pairing suggests that you might find success by balancing established practices with new ideas in your work. The Hierophant encourages you to learn from tradition while also being open to innovative approaches.'\n" +
                "5,7,'The Hierophant`s guidance combines with the Chariot`s drive and determination to achieve career goals. This pairing suggests that you`ll be able to learn from experienced mentors or colleagues while also taking initiative and focusing on achieving your professional ambitions.'\n" +
                "5,8,'This pairing signifies that your inner strength and resilience will help you overcome challenges at work. The Hierophant`s role as a teacher might involve guiding others with compassion and helping them develop their own inner strength.'\n" +
                "5,9,'Taking time for introspection and independent learning can be valuable for growth. This pairing suggests that a period of solitary study or reflection might challenge your existing beliefs or lead you to discover new approaches to your work. '\n" +
                "5,10,'Change and unexpected events are inevitable in the workplace. This pairing suggests that established systems or traditional practices might need to adapt to changing circumstances.'\n" +
                "5,11,'This pairing signifies that fairness, ethics, and equal opportunity are important aspects of a healthy work environment. The Hierophant`s role as a teacher or guide emphasizes the importance of upholding ethical practices and ensuring fairness for all.'\n" +
                "5,12,'Taking a different perspective or a pause in your traditional approach can be beneficial. This pairing suggests that stepping back and considering alternative viewpoints might lead to new and innovative ways to teach, learn, and approach your work. '\n" +
                "5,13,'Death doesn`t always signify literal endings; it can represent transformation. This pairing suggests that there might be a significant change in established practices or traditional ways of doing things in your work environment.'\n" +
                "5,14,'Finding balance and working effectively with others is key to successful teaching and guidance. This pairing suggests that you might need to find a middle ground between competing traditions or viewpoints.'\n" +
                "5,15,'The Devil can represent temptation, manipulation, or clinging to outdated practices. This pairing suggests that you might face a situation where someone`s teaching or guidance is unethical or manipulative.'\n" +
                "5,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that established systems or traditional ways of doing things in your work environment might experience a sudden setback.'\n" +
                "5,17,'This pairing signifies teaching and guidance that inspires hope and maintains a positive vision for the future, even in challenging times. The Hierophant`s knowledge and experience offer a sense of direction and motivation for those learning from them.'\n" +
                "5,18,'The Moon signifies hidden knowledge, fears, and uncertainties. This pairing suggests that you might uncover previously unknown information or hidden aspects of established practices in your work environment.'\n" +
                "5,19,'This is a very positive sign for your role as a teacher or guide. It signifies successful teaching that has empowered others and led to positive outcomes. The Hierophant`s knowledge and experience have been instrumental in the growth and success of others in your work environment.'\n" +
                "5,20,'A period of self-reflection and reevaluation of your teaching or guidance methods might be necessary. This pairing suggests that you might need to assess your strengths and weaknesses as a teacher and identify areas for improvement.'\n" +
                "5,21,'This pairing signifies a culmination of your teaching or guidance, where you`ve successfully shared your knowledge and empowered others to achieve their goals. The Hierophant`s influence has had a lasting impact on those who learned from them.'\n" +
                "6,7,'This pairing suggests that a strong partnership will be crucial for achieving work goals. You and your partner(s) will need to combine your skills and focus your efforts to achieve success.'\n" +
                "6,8,'This pairing signifies that strong partnerships are built on compassion, understanding, and the ability to overcome challenges together. Both partners need to be willing to support and motivate each other through difficult times.'\n" +
                "6,9,'This pairing can have two interpretations. It might suggest that independent work styles might be beneficial for the project or partnership. Alternatively, it could indicate that a lack of communication or collaboration is hindering progress.'\n" +
                "6,10,'Change and unexpected events are inevitable in the workplace. This pairing suggests that your work partnership might need to adapt to changing circumstances or unexpected developments.'\n" +
                "6,11,'This pairing signifies that fairness, honesty, and respect are key components of a successful work partnership. Both partners need to be committed to ethical collaboration and treat each other with respect.'\n" +
                "6,12,'Taking a different perspective or making compromises can benefit partnerships. This pairing suggests that seeing things from your partner`s perspective or being willing to compromise on certain aspects of the project can lead to a more successful outcome.'\n" +
                "6,13,'Death doesn`t always signify literal endings; it can represent transformation. This pairing suggests that your work partnership might undergo a significant change. This could involve a restructuring, a change in roles, or even the dissolution of the partnership.'\n" +
                "6,14,'Finding balance and working effectively with your partner(s) is key to a successful collaboration. This pairing suggests that you might need to find a middle ground between competing ideas or priorities.'\n" +
                "6,15,'The Devil can represent temptation, manipulation, or unhealthy competition within a partnership. This pairing suggests that you might face a situation where your partner(s) are engaging in unethical behavior or prioritizing personal gain over the success of the collaboration.'\n" +
                "6,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that your work partnership might experience a major setback or unexpected challenge. '\n" +
                "6,17,'This pairing signifies a partnership that inspires hope and maintains a positive vision for the future, even in challenging times. The Lovers` focus on collaboration and attraction creates a strong foundation for success.'\n" +
                "6,18,'The Moon signifies hidden fears, uncertainties, and a lack of clarity. This pairing suggests that hidden issues or a lack of communication might be hindering your work partnership.'\n" +
                "6,19,'This is a very positive sign for your work partnership. It signifies a collaboration that has achieved success and earned recognition. The Lovers` focus on attraction and collaboration has led to a strong and productive partnership.'\n" +
                "6,20,'A period of self-reflection and reevaluation of your work partnership might be necessary. This pairing suggests that you and your partner(s) might need to assess the strengths and weaknesses of the collaboration and identify areas for improvement.'\n" +
                "6,21,'This pairing signifies a successful culmination of your work partnership, where you`ve achieved your goals and created something lasting together. The Lovers` influence has led to a successful and impactful collaboration.'\n" +
                "7,8,'This pairing signifies that your ambition is balanced with compassion and understanding. You`ll be able to overcome challenges with determination and perseverance, while also being considerate of others.'\n" +
                "7,9,'This pairing can have two interpretations. It might suggest that independent work and focused concentration will be key to achieving your goals. Alternatively, it could indicate a lack of clear direction or a need for collaboration.'\n" +
                "7,10,'Change and unexpected events are inevitable in the workplace. This pairing suggests that you`ll need to be adaptable and adjust your strategy to navigate unforeseen circumstances while still achieving your goals.'\n" +
                "7,11,'This pairing signifies that fairness, honesty, and ethical conduct are important aspects of achieving your goals. The Chariot`s drive is balanced by Justice`s emphasis on fair play and working with integrity.'\n" +
                "7,12,'Taking a different perspective or pausing to reflect on your goals can be beneficial. This pairing suggests that taking a step back and considering alternative approaches might lead to a more efficient or successful way to achieve your goals.'\n" +
                "7,13,'Death doesn`t always signify literal endings; it can represent transformation. This pairing suggests that your goals or ambitions might undergo a significant change. This could involve a new direction, a promotion, or a change in the overall project you`re working on.'\n" +
                "7,14,'Finding balance and flexibility is key to achieving your goals. This pairing suggests that you might need to adjust your initial plan or find a middle ground between competing priorities. '\n" +
                "7,15,'The Devil can represent temptation, obsession, or pursuing goals at any cost. This pairing suggests that your ambition might be clouded by unethical behavior or a focus on personal gain over the overall project`s success.'\n" +
                "7,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that your plans or goals might experience a major setback or unexpected challenge. '\n" +
                "7,17,'This pairing signifies that your ambition is fueled by hope and a positive vision for the future. The Chariot`s focus is balanced by the Star`s reminder to maintain a long-term vision and stay motivated even through challenges.'\n" +
                "7,18,'The Moon signifies hidden fears, uncertainties, and a lack of clarity. This pairing suggests that unforeseen obstacles or a lack of information might hinder your progress.'\n" +
                "7,19,'This is a very positive sign for your goals. It signifies that your ambition and determination have led to success and recognition. The Chariot`s focus has helped you achieve your goals in a way that is both ambitious and successful.'\n" +
                "7,20,'A period of self-reflection and reevaluation of your goals and strategies might be necessary. This pairing suggests that you might need to assess your progress and identify areas for improvement.'\n" +
                "7,21,'This pairing signifies a successful culmination of your efforts, where you`ve achieved your goals and created something lasting. The Chariot`s focus and determination have led to a successful and impactful outcome. '\n" +
                "8,9,'This pairing suggests that solitude and self-reflection can be a source of strength when facing challenges at work. Taking time for introspection can help you identify your inner resources and develop strategies for overcoming obstacles.'\n" +
                "8,10,'Change and unexpected events are inevitable in the workplace. This pairing suggests that your inner strength will be crucial for adapting to changing circumstances and overcoming unforeseen challenges.'\n" +
                "8,11,'This pairing signifies that fairness, ethics, and standing up for what`s right can require inner strength. You might need to use your resilience to advocate for yourself or others in the face of unfair treatment.'\n" +
                "8,12,'Taking a different perspective or offering a new solution can demonstrate strength. This pairing suggests that approaching a challenge from a different angle or having patience with a situation can lead to a successful outcome.'\n" +
                "8,13,'Death doesn`t always signify literal endings; it can represent transformation. This pairing suggests that challenging situations require resilience and the inner strength to navigate through change.'\n" +
                "8,14,'Finding balance and avoiding extremes is key to overcoming challenges. This pairing suggests that using your inner strength to find a middle ground between competing demands or opposing viewpoints can lead to a more effective solution.'\n" +
                "8,15,'The Devil can represent temptation, manipulation, or unethical behavior. This pairing suggests that you might face a situation where someone`s actions are unethical or manipulative.'\n" +
                "8,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that a sudden setback or unexpected challenge can test your resilience. However, your inner strength will help you rebuild and overcome the obstacles.'\n" +
                "8,17,'This pairing signifies that your inner strength is fueled by hope and a positive vision for the future. This optimism will help you persevere through challenges and maintain your motivation.'\n" +
                "8,18,'The Moon signifies hidden fears, uncertainties, and a lack of clarity. This pairing suggests that facing unknown challenges requires inner strength. You might need to tap into your resilience to navigate through a period of uncertainty.'\n" +
                "8,19,'This is a very positive sign. It signifies that your inner strength and resilience have helped you overcome challenges and achieve success. You`ve emerged from difficult situations stronger and more confident.'\n" +
                "8,20,'A period of self-reflection might be necessary to recognize your own inner strength and resilience. This pairing suggests that you might need to acknowledge the challenges you`ve overcome and celebrate your own resourcefulness.'\n" +
                "8,21,'This pairing signifies that your inner strength has helped you achieve a sense of completion and a lasting impact in your work. You`ve overcome challenges and created something positive and enduring.'\n" +
                "9,10,'Change and unexpected events are inevitable in the workplace. This pairing suggests that your preference for solitude or independent work might need to adapt to changing circumstances.'\n" +
                "9,11,'This pairing signifies that fairness and ethical behavior are important, even when working independently. You might need to advocate for yourself or others, even if it means going against the grain or working alone to ensure fair treatment.'\n" +
                "9,12,'Taking a different perspective can be valuable, even when working alone. This pairing suggests that solitude and introspection can lead to new ideas and innovative solutions. Taking a step back from the situation can offer a fresh perspective.'\n" +
                "9,13,'Death doesn`t always signify literal endings; it can represent transformation. This pairing suggests that a period of solitude or independent work might lead to a significant change in your approach to work.'\n" +
                "9,14,'Finding balance between solitude and collaboration can be key to success. This pairing suggests that you might need to find a way to integrate your independent work style with the need for collaboration or input from others.'\n" +
                "9,15,'The Devil can represent temptation, manipulation, or unethical behavior. This pairing suggests that working in isolation might make you more susceptible to temptation or manipulation.'\n" +
                "9,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that your preference for solitude or independent work might be disrupted by unexpected events. '\n" +
                "9,17,'This pairing signifies that solitude and introspection can be a source of hope and inspiration. Taking time for reflection can help you develop a positive vision for the future, even when working independently.'\n" +
                "9,18,'The Moon signifies hidden fears, uncertainties, and a lack of clarity. This pairing suggests that working in isolation might amplify feelings of doubt or uncertainty.'\n" +
                "9,19,'This is a very positive sign for your independent work. It signifies that your dedication and focus while working alone have led to success and recognition. Your solitude has been productive and yielded positive results.'\n" +
                "9,20,'A period of self-reflection might be necessary to assess the effectiveness of your independent work style. This pairing suggests that you might need to evaluate whether your approach is still serving you well or if adjustments are needed.'\n" +
                "9,21,'This pairing signifies that a period of independent work has culminated in a successful outcome. You`ve achieved your goals and might now be ready to share your knowledge or collaborate with others.'\n" +
                "10,11,'Change and unexpected events can disrupt established practices. This pairing suggests that adapting work practices to ensure fairness and ethical treatment for everyone will be crucial during times of change.'\n" +
                "10,12,'Taking a different perspective can be valuable during unexpected events. This pairing suggests that seeing things from a new angle might lead to innovative solutions or help you adapt to changing circumstances.'\n" +
                "10,13,'Death doesn`t always signify literal endings; it can represent transformation. This pairing signifies that significant changes or unexpected events might lead to a major transformation in your work environment or career path. '\n" +
                "10,14,'Finding balance and flexibility is key to navigating change. This pairing suggests that you might need to find a middle ground between established practices and necessary adaptations during times of upheaval.'\n" +
                "10,15,'The Devil can represent temptation, manipulation, or unethical behavior. This pairing suggests that unexpected events or changes might create opportunities for someone to act unethically. Be vigilant and uphold ethical standards during times of uncertainty.'\n" +
                "10,16,'Both cards represent change, but the Tower signifies a sudden and dramatic upheaval. This pairing signifies that a major disruption or unexpected event will significantly impact your work environment.'\n" +
                "10,17,'This pairing signifies that maintaining a positive vision for the future is important even when facing unexpected events. The Star`s hopefulness can help you stay motivated and optimistic during times of change.'\n" +
                "10,18,'The Moon signifies hidden fears, uncertainties, and a lack of clarity. This pairing suggests that unexpected events might create confusion or a lack of information. Be patient and seek out clarification to navigate uncertainty effectively.'\n" +
                "10,19,'This is a positive sign. It signifies that your adaptability and ability to navigate change have led to success. You`ve emerged from unexpected events in a stronger position.'\n" +
                "10,20,'A period of self-reflection might be necessary to assess how you handled change and unexpected events. This pairing suggests that you might need to evaluate your adaptability and identify areas for improvement.'\n" +
                "10,21,'This pairing signifies that a significant cycle of change has come to an end. You might have adapted to a new work environment, embraced a new career path, or completed a project that involved significant change.'\n" +
                "11,12,'This pairing suggests that considering all perspectives and finding a balanced approach is crucial for making fair decisions. Taking a different viewpoint can help ensure everyone is treated justly.'\n" +
                "11,13,'Death signifies transformation, which can involve changes in company policies, leadership, or work practices. This pairing suggests that these changes should be implemented with fairness and ethical considerations in mind.'\n" +
                "11,14,'Finding balance and compromise is key to achieving fairness. This pairing signifies that you might need to find a middle ground between competing interests or viewpoints to ensure everyone is treated justly.'\n" +
                "11,15,'The Devil represents temptation and unethical behavior. This pairing suggests that you might face a situation where someone is acting unethically or manipulating the system. Justice encourages you to challenge this behavior and advocate for fair treatment for all.'\n" +
                "11,16,'he Tower signifies sudden disruption and upheaval. This pairing suggests that a major event might disrupt established systems or practices, potentially leading to unfair treatment.'\n" +
                "11,17,'This pairing signifies that maintaining a hopeful vision for a fair and ethical work environment is important. The Star`s hopefulness can inspire you to keep advocating for fair treatment, even when faced with challenges.'\n" +
                "11,18,'The Moon signifies hidden truths, uncertainties, and a lack of clarity. This pairing suggests that there might be hidden factors or unfair practices at play. Justice encourages you to seek out the truth and advocate for fair treatment for those who might be negatively impacted.'\n" +
                "11,19,'This is a very positive sign. It signifies that your commitment to fairness and ethical behavior has led to a successful outcome for all involved. Justice has been upheld, and everyone has benefited.'\n" +
                "11,20,'A period of self-reflection might be necessary to assess your own actions and contributions to a fair and ethical work environment. This pairing suggests that you might need to consider whether you`ve upheld fair practices and identify areas where you can improve.'\n" +
                "11,21,'This pairing signifies that your commitment to fairness and ethical treatment has had a lasting impact on your work environment. You`ve helped create a system that is fair and beneficial for all involved.'\n" +
                "12,13,'This pairing signifies that a significant change or transformation might require some sacrifice. You might need to let go of old habits, projects, or ways of thinking to embrace new beginnings.'\n" +
                "12,14,'Finding balance and compromise is key to implementing new approaches. This pairing suggests that you might need to find a middle ground between established practices and innovative ideas to create a successful new way of working.'\n" +
                "12,15,'The Devil represents temptation and clinging to the past. This pairing suggests that you might be tempted to revert to old ways of working, even though change is necessary.'\n" +
                "12,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that a major event might force you to adopt a new perspective on your work. The Hanged Man encourages you to see this as an opportunity to find new and innovative solutions.'\n" +
                "12,17,'This pairing signifies that maintaining a positive vision for the future is important even when adopting a new approach. The Star`s hopefulness can inspire you to stay motivated and optimistic as you explore new ways of working.'\n" +
                "12,18,'The Moon signifies hidden fears, uncertainties, and a lack of clarity. This pairing suggests that implementing a new approach might encounter unforeseen obstacles. The Hanged Man encourages you to be adaptable and adjust your perspective to navigate these challenges.'\n" +
                "12,19,'This is a very positive sign. It signifies that your willingness to adopt a new perspective and embrace change has led to success. The Hanged Man`s innovative approach has yielded positive results.'\n" +
                "12,20,'A period of self-reflection might be necessary to assess the effectiveness of your new approach. This pairing suggests that you might need to evaluate whether your new perspective has been beneficial and identify areas for further refinement.'\n" +
                "12,21,'This pairing signifies that your willingness to adopt a new perspective and embrace change has led to a successful outcome. You`ve completed a project or initiative using an innovative approach, and its impact will be long-lasting.'\n" +
                "13,14,'This pairing suggests that transformation often requires finding balance and avoiding extremes. You might need to find a middle ground between holding onto the past and fully embracing change.'\n" +
                "13,15,'The Devil represents temptation and clinging to unhealthy situations. This pairing suggests that a transformation might be necessary to break free from an unethical work environment or unproductive habits. '\n" +
                "13,16,'Both cards signify change, but Death is more transformative while the Tower is disruptive. This pairing suggests that a sudden event or upheaval might force a significant transformation in your work environment or career path'\n" +
                "13,17,'This pairing signifies that maintaining a positive vision for the future is important even during a period of transformation. The Star`s hopefulness can inspire you to stay motivated and optimistic as you navigate change.'\n" +
                "13,18,'The Moon signifies hidden fears, uncertainties, and a lack of clarity. This pairing suggests that transformation can be accompanied by feelings of doubt and confusion.'\n" +
                "13,19,'This is a very positive sign. It signifies that a period of transformation has led to a successful outcome. You`ve let go of the past, embraced change, and achieved something positive in your work.'\n" +
                "13,20,'A period of self-reflection might be necessary to assess how you handled the transformation. This pairing suggests that you might need to evaluate what you`ve learned from the experience and identify areas for personal growth.'\n" +
                "13,21,'This pairing signifies that a significant transformation has come to an end. You`ve let go of the past, embraced change, and completed a project or chapter in your work life. The World suggests a sense of closure and the potential beginning of something new.'\n" +
                "14,15,'The Devil represents temptation and clinging to unhealthy situations. This pairing suggests that you might face a situation where someone is acting unethically or manipulating the system.'\n" +
                "14,16,'The Tower signifies sudden disruption and upheaval. This pairing suggests that a major event might have created conflict or tension in the workplace.'\n" +
                "14,17,'This is a positive pairing. It signifies that maintaining a balanced approach and fostering hope can lead to a more harmonious work environment. Temperance and the Star work together to create a space for collaboration and understanding.'\n" +
                "14,18,'The Moon signifies hidden fears, uncertainties, and a lack of clarity. This pairing suggests that navigating a situation with conflicting information or uncertainties requires a balanced approach. '\n" +
                "14,19,'This is a very positive sign. It signifies that your ability to find balance and avoid extremes has led to success. Temperance`s focus on moderation has yielded positive results.'\n" +
                "14,20,'A period of self-reflection might be necessary to assess your ability to find balance and avoid extremes. This pairing suggests that you might need to evaluate whether you`ve been a moderating influence and identify areas for improvement.'\n" +
                "14,21,'This pairing signifies that your ability to find balance and avoid extremes has had a lasting impact on your work environment. You`ve helped create a system that is fair and beneficial for all involved.'\n" +
                "15,16,'This pairing suggests that a sudden event or upheaval might expose unethical behavior or manipulation that has been happening under the surface. The Tower`s disruption can bring hidden truths to light.'\n" +
                "15,17,'This pairing signifies a struggle between temptation and hope. The Star`s positive influence can help you resist the allure of unethical shortcuts or manipulation. It encourages you to maintain hope for a better work environment.'\n" +
                "15,18,'This pairing suggests that there might be hidden secrets or deceptive practices at play. The Moon`s influence amplifies the Devil`s themes of manipulation and makes it difficult to see the truth. Be cautious and seek out reliable information.'\n" +
                "15,19,'This is a very positive sign. It signifies that you`ve successfully resisted temptation and exposed unethical behavior. The Sun`s light shines through the darkness, revealing the truth and paving the way for a more positive work environment.'\n" +
                "15,20,'A period of self-reflection might be necessary to assess your own role in the situation. This pairing suggests that you might need to consider whether you`ve been influenced by the Devil`s temptations or if you`ve spoken up against unethical behavior.'\n" +
                "15,21,'This pairing signifies that you`ve broken free from a manipulative or unethical work environment. You`ve achieved a sense of completion by leaving behind a negative situation and are ready to move on to new beginnings.'\n" +
                "16,17,'This pairing suggests that even after a sudden disruption, maintaining a positive vision for the future is important. The Star`s hopefulness can inspire you to stay motivated and optimistic as you rebuild.'\n" +
                "16,18,'The Moon signifies hidden fears, uncertainties, and a lack of clarity. This pairing suggests that the disruption caused by The Tower might lead to confusion and a lack of information. Be patient and seek out reliable information to navigate the uncertainty.'\n" +
                "16,19,'This is a positive sign. It signifies that even after a major disruption, you can emerge stronger and achieve success. The Tower`s destruction can pave the way for something new and positive to be built.'\n" +
                "16,20,'A period of self-reflection might be necessary to assess the impact of the disruption. This pairing suggests that you might need to evaluate how you handled the situation and identify lessons learned for the future.'\n" +
                "16,21,'This pairing signifies that the disruption caused by The Tower has run its course. You`ve rebuilt, adapted, and reached a point of completion. The World suggests a new beginning built on the lessons learned from the upheaval.'\n" +
                "17,18,'The Moon signifies hidden fears, uncertainties, and a lack of clarity. This pairing suggests that even when facing challenges or uncertainties, maintaining a positive vision can help you stay motivated and navigate difficulties.'\n" +
                "17,19,'This is a very positive sign. It signifies that your hope and optimism have led to success and fulfillment in your work. The Star`s inspiration has paved the way for a positive outcome.'\n" +
                "17,20,'A period of self-reflection might be necessary to assess the role of hope in your work. This pairing suggests that you might need to consider how your optimism and belief in a better future have impacted your actions and decisions.'\n" +
                "17,21,'This pairing signifies that your positive vision and hope have had a lasting impact on your work environment or a project. You`ve inspired others and helped create something positive and enduring. '\n" +
                "18,19,'This pairing signifies the potential for hidden truths to come to light. The Sun`s brightness can illuminate the illusions and uncertainties represented by The Moon.'\n" +
                "18,20,'A period of self-reflection might be necessary to assess awareness of hidden truths. This pairing suggests that you might need to consider whether you`ve been ignoring intuition or overlooking crucial information.'\n" +
                "18,21,'This pairing signifies that despite hidden truths or uncertainties, a sense of completion can be achieved. You might have navigated a period of confusion or lack of clarity and emerged with a sense of closure. '\n" +
                "19,20,'A period of self-reflection might be necessary to assess your contribution to the success. This pairing suggests that you might need to acknowledge your role in achieving a positive outcome and identify areas for continued growth.'\n" +
                "19,21,'This is a very positive pairing. It signifies that your work has culminated in a successful and fulfilling outcome. The Sun`s positive influence has led to a lasting impact, and The World suggests a sense of completion and a positive legacy.'\n" +
                "20,21,'Judgement and the World together signify a successful completion, a period of reflection, and the potential for exciting new beginnings in your work life. Celebrate your achievements, learn from your experiences, and embrace the opportunities that lie ahead.'"
    }
}